# Generated by Django 3.1.7 on 2021-03-08 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shophome', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='customername',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='merchant',
            name='selling',
        ),
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(max_length=200)),
                ('selldetail', models.TextField()),
                ('dates', models.DateField()),
                ('selling', models.FloatField()),
                ('shopkipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shophome.merchant')),
            ],
        ),
    ]
