# Generated by Django 3.1.7 on 2021-03-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophome', '0003_auto_20210308_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='dates',
            field=models.DateField(auto_now=True),
        ),
    ]
