# Generated by Django 3.1.7 on 2021-03-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophome', '0004_auto_20210308_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customername',
            field=models.CharField(default='unknown', max_length=200),
        ),
        migrations.AlterField(
            model_name='customers',
            name='selldetail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
