# Generated by Django 3.1.7 on 2021-03-08 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shophome', '0006_auto_20210308_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='shopkipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shophome.merchant'),
        ),
    ]
