# Generated by Django 3.1.7 on 2021-03-08 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shophome', '0007_auto_20210308_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='shopkipper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
