# Generated by Django 3.1.7 on 2021-03-08 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shophome', '0009_auto_20210308_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customers',
            name='shopkipper',
        ),
    ]
