# Generated by Django 3.1.7 on 2021-03-08 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shophome', '0010_remove_customers_shopkipper'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='shopkipper',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='shophome.merchant'),
            preserve_default=False,
        ),
    ]
