# Generated by Django 3.1.7 on 2021-03-08 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shophome', '0012_delete_customers'),
    ]

    operations = [
        migrations.CreateModel(
            name='customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(default='unknown', max_length=200)),
                ('selldetail', models.TextField(blank=True, null=True)),
                ('dates', models.DateField(auto_now=True)),
                ('selling', models.FloatField()),
                ('shopkipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shopname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shophome.merchant')),
            ],
        ),
    ]
