# Generated by Django 3.1.7 on 2021-03-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shophome', '0014_auto_20210309_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='selling',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
